logo:
  subtitle: 荣耀三班 绝非一般 励志笃行 敢为人先|九年今朝少年狂 艳压群芳绽陈仓

menubar:
  columns: 3
  items:
    - id: post
      title: 文章
      url: /
    - id: maintain
      title: 维护
      url: /maintain
    - id: about
      title: 关于
      url: /about

article:
  type: story

style:
  font-family:
    logo: AlimamaDongFangDaKai
    body: LXGW WenKai Screen
  leftbar:
    background-image: "linear-gradient(60deg, #fdb, #da9)"

inject:
  head:
    - <link rel="stylesheet" href="https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont/style.min.css" media="none" onload="this.media='all'">
    - <link rel="stylesheet" href="/static/font.css">
    - <link rel="stylesheet" href="//blog.zhilu.cyou/static/patch.css">
