logo:
  subtitle: 荣耀三班 绝非一般 励志笃行 敢为人先

menubar:
  columns: 2
  items:
    - id: post
      title: 文章
      url: /
    - id: about
      title: 关于
      url: /about/

style:
  sidebar:
    background: "linear-gradient(60deg, #fdb, #da9)"
